# Generated by Django 5.2 on 2025-05-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Manutenção')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='maquinas.maquina')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
