# Generated by Django 5.2 on 2025-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manutencoes",
            "0003_remove_manutencao_description_manutencao_descricao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencao",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
    ]
