# Generated by Django 5.2 on 2025-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manutencoes", "0004_alter_manutencao_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencao",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
    ]
