# Generated by Django 5.2 on 2025-05-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_cargo_permissao_alter_user_cargo_cargo_permissoes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargo",
            options={"verbose_name": "Cargo", "verbose_name_plural": "Cargos"},
        ),
        migrations.AlterModelOptions(
            name="permissao",
            options={"verbose_name": "Permissão", "verbose_name_plural": "Permissões"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuário", "verbose_name_plural": "Usuários"},
        ),
    ]
