# Generated by Django 5.2 on 2025-05-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "condicao",
                    models.CharField(
                        choices=[("Nova", "Nova"), ("Usada", "Usada")],
                        max_length=10,
                        verbose_name="Condicao",
                    ),
                ),
                ("ano", models.IntegerField(verbose_name="Ano")),
                (
                    "numero_de_serie",
                    models.CharField(
                        default="Sem Serial",
                        max_length=255,
                        verbose_name="Numero de Série",
                    ),
                ),
            ],
            options={
                "ordering": ["-ano"],
            },
        ),
        migrations.CreateModel(
            name="MaquinaImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="maquinas/imagens/")),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="maquinas.maquina",
                    ),
                ),
            ],
        ),
    ]
